//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrayFog_Framework_Pak {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResPakBat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResPakBat() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StrayFog_Framework_Pak.ResPakBat", typeof(ResPakBat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 @echo on
        ///set version=1.0
        ///set platform=Windows
        ///set projectdir=F:/UE4Frame_4.18/StrayFog_Framework/
        ///set enginedir=D:/Program Files (x86)/Epic Games/UE_4.18/Engine/
        ///set unrealPakExe=D:/Program Files (x86)/Epic Games/UE_4.18/Engine/Binaries/Win64/UnrealPak.exe
        ///set createPakFileName=F:/UE4Frame_4.18/StrayFog_Framework/BatAndPak/2018.04.12-16.44.37.pak
        ///set createFileName=D:/Program Files (x86)/Epic Games/UE_4.18/Engine/Programs/AutomationTool/Saved/Logs/PakList_Framework-WindowsNoEditor_0_P.txt
        ///set abslog [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Pak_Create {
            get {
                return ResourceManager.GetString("Pak_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @echo on
        ///set unrealPakExe=D:/Program Files (x86)/Epic Games/UE_4.18/Engine/Binaries/Win64/UnrealPak.exe
        ///set createPakFileName=$PakPath$
        ///set extractPath=F:/UE4Frame_4.18/StrayFog_Framework/BatAndPak/2018.04.12-16.44.37_Extract
        ///&quot;%unrealPakExe%&quot; &quot;%createPakFileName%&quot; -Extract &quot;%extractPath%&quot; 
        ///exit 的本地化字符串。
        /// </summary>
        internal static string Pak_Extract {
            get {
                return ResourceManager.GetString("Pak_Extract", resourceCulture);
            }
        }
    }
}
